#!/usr/bin/env bash
PID=$(ps aux | grep '[s]hodan' | awk '{print $2}')
kill $PID
wait $PID
SHODAN_HOME=/home/ec2-user/shodan
mkdir -p $SHODAN_HOME/bin/previous
mv $SHODAN_HOME/bin/*.jar $SHODAN_HOME/bin/previous