#!/usr/bin/env bash

# STOP APPLICATION
APP=[s]hodan
# Generic code below which can be reused (copy-paste)
PID=$(ps aux | grep ${APP} | awk '{print $2}')
if [ ! -z "${PID}" ]; then
  kill ${PID}
  while kill -0 ${PID} 2> /dev/null; do sleep 1; done;
fi

# BACKUP JAR FILE
APP_HOME=/home/ec2-user/shodan
mkdir -p ${APP_HOME}/bin/previous
mv ${APP_HOME}/bin/*.jar ${APP_HOME}/bin/previous